name: 'unai'
services:
  web:
    container_name: 'unai'
    image: 'ghcr.io/shba007/unai-web:latest'
    restart: on-failure:3
    env_file:
      - .env.prod
    ports:
      - 3200:8000

  api:
    container_name: 'unai'
    image: 'ghcr.io/shba007/unai-api:latest'
    restart: on-failure:3
    env_file:
      - .env.prod
    ports:
      - 2300:8000

  tf-serve:
    container_name: 'unai'
    image: 'tensorflow/serving:2.18.0'
    restart: on-failure:3
    ports:
      - 1510:8500
      - 1511:8501
    volumes:
      - type: bind
        source: models
        target: /models
    command: '--model_config_file=/models/models.config'
